create table if not exists public.leads (
    id bigint generated by default as identity primary key,
    client_name text not null,
    phone text not null,
    phone_normalized text not null unique,
    lead_source text not null
        check (lead_source in ('cold', 'warm')),
    responsible text not null
        check (responsible in ('lead_generator', 'sales_manager')),
    deal_stage text not null
        check (
            deal_stage in (
                'new',
                'qualified',
                'consultation_scheduled',
                'rejected'
            )
        ),
    technical_spec_requested boolean not null,
    created_at timestamptz not null
);

create table if not exists public.lead_stage_history (
    id bigint generated by default as identity primary key,
    lead_id bigint not null
        references public.leads (id) on delete cascade,
    previous_stage text not null,
    new_stage text not null,
    changed_at timestamptz not null
);

create index if not exists idx_history_lead_id
on public.lead_stage_history (lead_id, changed_at desc, id desc);

create index if not exists idx_leads_created_at
on public.leads (created_at desc, id desc);

alter table public.leads enable row level security;
alter table public.lead_stage_history enable row level security;

revoke all on table public.leads from anon, authenticated;
revoke all on table public.lead_stage_history from anon, authenticated;
revoke all on sequence public.leads_id_seq from anon, authenticated;
revoke all on sequence public.lead_stage_history_id_seq
from anon, authenticated;
